modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.tacz.mixins.json"

[[mixins]]
config = "${mod_id}.sbw.mixins.json"

[[mods]]
modId = "${mod_id}"
logoFile = "modicon.png"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# PlayerRevive dependency - required for this mod to function
[[dependencies."${mod_id}"]]
modId = "playerrevive"
mandatory = true
versionRange = "[1.9.6,)"
ordering = "AFTER"
side = "BOTH"

# TaCZ dependency - optional
[[dependencies."${mod_id}"]]
modId = "tacz"
mandatory = false
versionRange = "[1.0.3,)"
ordering = "AFTER"
side = "BOTH"

# SuperbWarfare dependency - optional
[[dependencies."${mod_id}"]]
modId = "superbwarfare"
mandatory = false
versionRange = "[0.8.0,)"
ordering = "AFTER"
side = "BOTH"

